#!/bin/bash

if [[ "$OSTYPE" == "msys" ]]; then
	source buildscripts/build_dais_mingw
elif [[ "$OSTYPE" == "darwin"* ]]; then
	source buildscripts/build_dais_osx
else
	echo "Unknown build for platform" "$OSTYPE"
fi
